### ISSUE TITLE
Indian tweets

### ISSUE THREAD

**Issue by dhruvshetty0103** [kartikmohan123/Covid19-Sentiment-Analysis#1]
I have a question about the tweets. How you extracted tweets related to Indians or from Indian Region from the reference dataset

**Comment by mohan-kartik** [comment]
I have filtered the tweets using country code of India - IN. 

Following is the code for the same.
tweet =tweet[(tweet.country_code == "IN")].reset_index(drop = True)

The same has been implemented in the notebook.

**Comment by dhruvshetty0103** [comment]
oh ok ok got it thanks a lot
